### ISSUE TITLE
All, active, completed filters redirect to 404

### ISSUE THREAD

**Issue by mLuby** [gdi2290/angular2do#1]
![screen shot 2015-02-09 at 12 58 35 pm](https://cloud.githubusercontent.com/assets/2483420/6115595/84428c1a-b05b-11e4-9771-f06de413e82e.png)

**Comment by PatrickJS** [comment]
yeah that's a known issue atm until I build out the $location service for angular2 and update zone.js to watch location path/hash. The styles change correctly but you have to manually tell the change-detection. For this case clicking on the link then toggling a todo does this. To fix that I would need to update zone.js. The other issue is hash prop support which means I need to either build $location or create a TodoStorage service to manage the todos or even create an angular2 filter

**Comment by huttj** [comment]
You have [a hardcoded base tag](https://github.com/gdi2290/angular2do/blob/gh-pages/index.html#L5) that is changing all of the links, too:

```
<base href="https://cdn.rawgit.com/gdi2290/angular2do/gh-pages/"></base>
```

**Comment by PatrickJS** [comment]
yeah I did that due to network errors from hosting it free on github. I'll fix the filters

**Comment by PatrickJS** [comment]
@mLuby @huttj I updated the repo so the filters are working. I had to rip out firebase adapter in order to manage the state correctly. Updating the hashbang so state is maintained on refresh would have to be done via creating a Location service or updating zone.js
